title: FormanPacific
csp: >-
  default-src 'self';
  script-src 'self' 'unsafe-inline'
    https://alcdn.msauth.net
    https://cdn.jsdelivr.net
    https://www.googletagmanager.com
    https://www.google-analytics.com
    https://googleads.g.doubleclick.net;
  style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net;
  img-src 'self' data: https:;
  font-src 'self' data: https://cdn.jsdelivr.net;
  connect-src 'self'
    https://roadandrescue.sharepoint.com
    https://login.microsoftonline.com
    https://www.googletagmanager.com
    https://www.google-analytics.com;
  frame-src 'self' https://login.microsoftonline.com https://www.googletagmanager.com;
  base-uri 'self'; form-action 'self'; object-src 'none'; worker-src 'self' blob:;
  upgrade-insecure-requests

